server:
  port : 8082

spring:
  microtx:
    coordinator-url: http://localhost:9000/api/v1
    participant-url: http://localhost:8082
    propagation-active: true
    http-client-connection-pool-size: 60
    xa-transaction-timeout: 60000
    xa-resource-manager-id: 174A5FF2-D8B1-47B0-AF09-DA5AFECA2F61
    xa-xa-support: true
    xa-llr-support: false
    xa-lrc-support: false
    xa-llr-delete-commit-record-interval: 720000
    xa-promotable-active: false
    xa-rac-active: false
    xa-weblogic-transaction-support: false
    xa-weblogic-namespace: weblogic