------------------------------------------------------------
-- Geofenced Promotion Demo - Tables
-- Creates all tables required for the workflow use case.
-- NOTE: Non-idempotent (no drops). Use cleanup.sql to remove.
------------------------------------------------------------

------------------------------------------------------------
-- USERS
------------------------------------------------------------
CREATE TABLE app_user (
  user_id              NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  user_name            VARCHAR2(100) NOT NULL,
  loyalty_tier         VARCHAR2(20),        -- BRONZE / SILVER / GOLD
  opted_in_promotions  VARCHAR2(3) DEFAULT 'Yes', -- Yes / No
  created_at           DATE DEFAULT SYSDATE
);

------------------------------------------------------------
-- PROMOTIONS
------------------------------------------------------------
CREATE TABLE promotion (
  promotion_id         NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  promotion_name       VARCHAR2(100) NOT NULL,
  required_tier        VARCHAR2(20),        -- NULL means any tier
  start_date           DATE NOT NULL,
  end_date             DATE NOT NULL,
  active_flag          VARCHAR2(3) DEFAULT 'Yes', -- Yes / No
  message_text         VARCHAR2(500)
);

------------------------------------------------------------
-- GEOFENCES
-- Simple bounding-box based geofence for demo purposes
------------------------------------------------------------
CREATE TABLE geofence (
  geofence_id          NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  geofence_name        VARCHAR2(100) NOT NULL,
  min_lat              NUMBER(9,6) NOT NULL,
  max_lat              NUMBER(9,6) NOT NULL,
  min_lon              NUMBER(9,6) NOT NULL,
  max_lon              NUMBER(9,6) NOT NULL,
  active_flag          VARCHAR2(3) DEFAULT 'Yes', -- Yes / No
  promotion_id         NUMBER,
  created_at           DATE DEFAULT SYSDATE,
  CONSTRAINT fk_geofence_promo
    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id)
);

------------------------------------------------------------
-- LOCATION EVENTS
------------------------------------------------------------
CREATE TABLE location_event (
  event_id             NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  event_lat            NUMBER(9,6) NOT NULL,
  event_lon            NUMBER(9,6) NOT NULL,
  event_time           DATE DEFAULT SYSDATE,
  source_system        VARCHAR2(50),
  CONSTRAINT fk_loc_user
    FOREIGN KEY (user_id) REFERENCES app_user(user_id)
);

------------------------------------------------------------
-- GEOFENCE MATCH RESULTS
------------------------------------------------------------
CREATE TABLE geofence_match_result (
  event_id             NUMBER PRIMARY KEY,
  geofence_id          NUMBER,
  match_flag           VARCHAR2(3),    -- Yes / No
  matched_at           DATE DEFAULT SYSDATE,
  CONSTRAINT fk_match_event
    FOREIGN KEY (event_id) REFERENCES location_event(event_id),
  CONSTRAINT fk_match_geofence
    FOREIGN KEY (geofence_id) REFERENCES geofence(geofence_id)
);

------------------------------------------------------------
-- PROMOTION ELIGIBILITY RESULTS
------------------------------------------------------------
CREATE TABLE promotion_eligibility_result (
  event_id             NUMBER PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  promotion_id         NUMBER,
  eligible_flag        VARCHAR2(3),    -- Yes / No
  eligibility_reason   VARCHAR2(500),
  evaluated_at         DATE DEFAULT SYSDATE,
  CONSTRAINT fk_elig_event
    FOREIGN KEY (event_id) REFERENCES location_event(event_id),
  CONSTRAINT fk_elig_user
    FOREIGN KEY (user_id) REFERENCES app_user(user_id),
  CONSTRAINT fk_elig_promo
    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id)
);

------------------------------------------------------------
-- PROMOTION EVENT LOG
------------------------------------------------------------
CREATE TABLE promotion_event_log (
  log_id               NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  event_id             NUMBER NOT NULL,
  user_id              NUMBER NOT NULL,
  geofence_id          NUMBER,
  promotion_id         NUMBER,
  action_taken         VARCHAR2(50),   -- e.g. GEOFENCE_MATCHED / NOTIFIED / NOT_ELIGIBLE
  details              VARCHAR2(1000),
  created_at           DATE DEFAULT SYSDATE,
  CONSTRAINT fk_pelog_event
    FOREIGN KEY (event_id) REFERENCES location_event(event_id),
  CONSTRAINT fk_pelog_user
    FOREIGN KEY (user_id) REFERENCES app_user(user_id),
  CONSTRAINT fk_pelog_geofence
    FOREIGN KEY (geofence_id) REFERENCES geofence(geofence_id),
  CONSTRAINT fk_pelog_promo
    FOREIGN KEY (promotion_id) REFERENCES promotion(promotion_id)
);

------------------------------------------------------------
-- NOTIFICATIONS
-- Stores latest notification payloads by user
------------------------------------------------------------
CREATE TABLE notification (
  notification_id      NUMBER GENERATED BY DEFAULT AS IDENTITY (NOCACHE) PRIMARY KEY,
  user_id              NUMBER NOT NULL,
  payload              JSON NOT NULL,
  created_at           DATE DEFAULT SYSDATE NOT NULL,
  CONSTRAINT fk_notification_user
    FOREIGN KEY (user_id) REFERENCES app_user(user_id)
);
