INSERT INTO ap_suppliers VALUES ('SUP-ACME','Acme Industrial Supply','ACTIVE',NULL,TRUNC(SYSDATE)-1240);
INSERT INTO ap_suppliers VALUES ('SUP-CROWNRIDGE','Crownridge Logistics','ACTIVE',NULL,TRUNC(SYSDATE)-880);
INSERT INTO ap_suppliers VALUES ('SUP-NORTHSTAR','Northstar Components','ACTIVE',NULL,TRUNC(SYSDATE)-640);
INSERT INTO ap_suppliers VALUES ('SUP-VERTEX','Vertex Machining','BLOCKED','Open quality dispute QD-4417; payments on hold',TRUNC(SYSDATE)-410);
INSERT INTO ap_contracts VALUES ('SUP-ACME','C-2280','s6.1',500,'USD','Separate freight charges up to USD 500 per shipment may be invoiced above the purchase order value.');
INSERT INTO ap_contracts VALUES ('SUP-CROWNRIDGE','C-2290','s7.2',1000,'USD','Separate freight charges up to USD 1,000 per shipment may be invoiced above the purchase order value.');
INSERT INTO ap_contracts VALUES ('SUP-NORTHSTAR','C-2291','s7.2',1000,'USD','Separate freight charges up to USD 1,000 per shipment may be invoiced above the purchase order value.');
INSERT INTO ap_contracts VALUES ('SUP-VERTEX','C-2305','s4.4',0,'USD','All charges must be included in the purchase order value. No separate freight is payable.');
INSERT INTO ap_purchase_orders VALUES ('PO-7800','SUP-ACME',12500,'USD','OPEN','Bearing assemblies, 500 units');
INSERT INTO ap_purchase_orders VALUES ('PO-7811','SUP-CROWNRIDGE',47900,'USD','OPEN','Palletised freight forwarding, Q3');
INSERT INTO ap_purchase_orders VALUES ('PO-7812','SUP-NORTHSTAR',47900,'USD','OPEN','Machined housings, 1,900 units');
INSERT INTO ap_purchase_orders VALUES ('PO-7818','SUP-ACME',9450,'USD','CLOSED','Hydraulic seals, 300 units');
INSERT INTO ap_purchase_orders VALUES ('PO-7820','SUP-VERTEX',22000,'USD','OPEN','Precision spindles, 100 units');
INSERT INTO ap_purchase_orders VALUES ('PO-7830','SUP-ACME',8300,'USD','OPEN','Consumable tooling, restock');
INSERT INTO ap_goods_receipts VALUES ('GR-88201','PO-7800','COMPLETE',500,500,TRUNC(SYSDATE)-9,NULL);
INSERT INTO ap_goods_receipts VALUES ('GR-88212','PO-7811','COMPLETE',1,1,TRUNC(SYSDATE)-11,NULL);
INSERT INTO ap_goods_receipts VALUES ('GR-88213','PO-7812','COMPLETE',1900,1900,TRUNC(SYSDATE)-7,NULL);
INSERT INTO ap_goods_receipts VALUES ('GR-88218','PO-7818','COMPLETE',300,300,TRUNC(SYSDATE)-22,NULL);
INSERT INTO ap_goods_receipts VALUES ('GR-88220','PO-7820','PARTIAL',100,60,TRUNC(SYSDATE)-5,'40 units rejected at inbound inspection');
INSERT INTO ap_goods_receipts VALUES ('GR-88230','PO-7830','COMPLETE',40,40,TRUNC(SYSDATE)-4,NULL);
INSERT INTO ap_bank_verifications VALUES ('SUP-ACME','COMPLETE','4471',NULL,TRUNC(SYSDATE)-512,TRUNC(SYSDATE)-510,'treasury-ops',NULL);
INSERT INTO ap_bank_verifications VALUES ('SUP-CROWNRIDGE','COMPLETE','8820',NULL,TRUNC(SYSDATE)-196,TRUNC(SYSDATE)-194,'treasury-ops',NULL);
INSERT INTO ap_bank_verifications VALUES ('SUP-NORTHSTAR','PENDING','9013','2264',TRUNC(SYSDATE)-3,NULL,NULL,'supplier portal self-service');
INSERT INTO ap_bank_verifications VALUES ('SUP-VERTEX','COMPLETE','3350',NULL,TRUNC(SYSDATE)-300,TRUNC(SYSDATE)-299,'treasury-ops',NULL);
INSERT INTO ap_paid_invoices VALUES ('INV-1049','INV-1049','SUP-ACME','PO-7818',9450,'USD',TRUNC(SYSDATE)-6,'PAY-55021');
INSERT INTO ap_paid_invoices VALUES ('INV-0902','INV-0902','SUP-CROWNRIDGE','PO-7790',15300,'USD',TRUNC(SYSDATE)-48,'PAY-54780');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1001','RECEIVED');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1047','RECEIVED');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1048','RECEIVED');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1052','RECEIVED');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1061','RECEIVED');
INSERT INTO ap_invoices (invoice_id,status) VALUES ('INV-1075','RECEIVED');
COMMIT;
