spring:
  application:
    name: api-gateway
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888/}
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/trip-service/**
#          filters:
#            - StripPrefix=2
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotelService/**
#          filters:
#            - StripPrefix=2
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flightService/**
#          filters:
#            - StripPrefix=2
---
spring:
  config:
    activate:
      on-profile: development
  cloud:
    gateway:
      routes:
        - id: trip-service
          uri: lb://trip-service
          predicates:
            - Path=/trip-service/**
        #          filters:
        #            - StripPrefix=2
        - id: hotel-service
          uri: lb://hotel-service
          predicates:
            - Path=/hotelService/**
        #          filters:
        #            - StripPrefix=2
        - id: flight-service
          uri: lb://flight-service
          predicates:
            - Path=/flightService/**
#          filters:
#            - StripPrefix=2
---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: default

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://config-server:8888
