workflowSampleServices:
  docProcessMcpServer:
    name: doc-process-mcp-server
    image: docker.io/library/doc-process-mcp-server:latest
    imagePullPolicy: IfNotPresent
    imagePullSecret: regcred
    replicaCount: 1

  loanComplianceService:
    name: loan-compliance-service
    image: docker.io/library/loan-compliance-service:latest
    imagePullPolicy: IfNotPresent
    imagePullSecret: regcred
    replicaCount: 1

  loanProcessingAgent:
    name: loan-processing-agent
    image: docker.io/library/loan-processing-agent:latest
    imagePullPolicy: IfNotPresent
    imagePullSecret: regcred
    replicaCount: 1
    enable_security: false
    # if security is enabled, provide token_url, client_id and client_secret
    token_url: http://<idp_root_url>:8080/realms/<realm_name>/protocol/openid-connect/token
    client_id: client_id
    client_secret: client_secret

  notificationService:
    name: notification-service
    image: docker.io/library/notification-service:latest
    imagePullPolicy: IfNotPresent
    imagePullSecret: regcred
    replicaCount: 1

  ocrService:
    name: ocr-service
    image: docker.io/library/ocr-microservice:latest
    imagePullPolicy: IfNotPresent
    imagePullSecret: regcred
    replicaCount: 1
