# Copyright (c) 2023, Oracle and/or its affiliates. **

# The Universal Permissive License (UPL), Version 1.0 **

# Subject to the condition set forth below, permission is hereby granted to any person obtaining a copy of this software, associated documentation and/or data
# (collectively the "Software"), free of charge and under any and all copyright rights in the Software, and any and all patent rights owned or freely licensable by each
# licensor hereunder covering either the unmodified Software as contributed to or provided by such licensor, or (ii) the Larger Works (as defined below), to deal in both
# ** (a) the Software, and (b) any piece of software and/or hardware listed in the lrgrwrks.txt file if one is included with the Software (each a "Larger Work" to which
# the Software is contributed by such licensors), **
# without restriction, including without limitation the rights to copy, create derivative works of, display, perform, and distribute the Software and make, use, sell,
# offer for sale, import, export, have made, and have sold the Software and the Larger Work(s), and to sublicense the foregoing rights on either these or other terms. **

# This license is subject to the following condition: The above copyright notice and either this complete permission notice or at a minimum a reference to the UPL must be
# included in all copies or substantial portions of the Software. **

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A
# PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
# CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
version: "3.9"
   
configs:
  my_tcs_config:
    file: ./tcs-docker-swarm.yaml

secrets:
  TMMSECRETKEY:
    external: true
  TMMPRIKEY:
    external: true
  TMMPUBKEY:
    external: true
  TMMPRIKEYPASSWD:
    external: true

services:
  otmm-tcs:
    image: "127.0.0.1:5000/tmm"
    ports:
      - "9000:9000"
    deploy:
      replicas: 1
    configs:
      - source: my_tcs_config
        target: /tcs.yaml
    entrypoint: ['/bin/sh', '-c', 'export TMMSECRETKEY=$$(cat /run/secrets/TMMSECRETKEY); export TMMPRIKEY=$$(cat /run/secrets/TMMPRIKEY); export TMMPUBKEY=$$(cat /run/secrets/TMMPUBKEY); export TMMPRIKEYPASSWD=$$(cat /run/secrets/TMMPRIKEYPASSWD); /app/tcs' ]
    environment:
      - CONFIG_FILE=/tcs.yaml
    secrets:
      - TMMSECRETKEY
      - TMMPRIKEY
      - TMMPUBKEY
      - TMMPRIKEYPASSWD
    
  # LRA Sample Application (services) below (Uncomment and edit to run)

  hotel:
    image: "127.0.0.1:5000/hotel:1.0"
    ports:
      - "8082:8082"
    deploy:
      replicas: 1
    environment:
      ORACLE_TMM_TCS_URL: "http://otmm-tcs:9000/api/v1"
      MP_LRA_COORDINATOR_URL: "http://otmm-tcs:9000/api/v1/lra-coordinator"
      MP_LRA_PARTICIPANT_URL: "http://hotel:8082"
      SERVICE_NAME: hotel
      ### MicroTx Springboot lib specific env
      SPRING_MICROTX_LRA_COORDINATOR_URL: "http://otmm-tcs:9000/api/v1/lra-coordinator"
      SPRING_MICROTX_LRA_PARTICIPANT_URL: "http://hotel:8082"

  flight:
    image: "127.0.0.1:5000/flight:1.0"
    ports:
      - "8083:8083"
    deploy:
      replicas: 1
    environment:
      ORACLE_TMM_TCS_URL: "http://otmm-tcs:9000/api/v1"
      ORACLE_TMM_CALLBACK_URL: "http://flight:8083"
      SERVICE_NAME: flight
      ### MicroTx Springboot lib specific env
      SPRING_MICROTX_LRA_COORDINATOR_URL: "http://otmm-tcs:9000/api/v1/lra-coordinator"
      SPRING_MICROTX_LRA_PARTICIPANT_URL: "http://flight:8083"

  trip-manager:
    image: "127.0.0.1:5000/trip-manager:1.0"
    ports:
      - "8081:8081"
    deploy:
      replicas: 1
    environment:
      ORACLE_TMM_TCS_URL: "http://otmm-tcs:9000/api/v1"
      MP_LRA_COORDINATOR_URL: "http://otmm-tcs:9000/api/v1/lra-coordinator"
      MP_LRA_PARTICIPANT_URL: "http://trip-manager:8081"
      SERVICE_NAME: trip-manager
      HOTEL_SERVICE_URL: "http://hotel:8082/hotelService/api/hotel"
      FLIGHT_SERVICE_URL: "http://flight:8083/flightService/api/flight"
      ### MicroTx Springboot lib specific env
      SPRING_MICROTX_LRA_COORDINATOR_URL: "http://otmm-tcs:9000/api/v1/lra-coordinator"
      SPRING_MICROTX_LRA_PARTICIPANT_URL: "http://trip-manager:8081"