spring:
  cloud:
    config:
      server:
        git:
#          uri: https://github.com/oracle-samples/microtx-samples/tree/main/lra/azure//spring-tripmanager-microservices-config
          default-label: master
