server:
  port : 8081

spring:
  application:
    name: department1
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
    show-sql: false
  datasource:
    url: "jdbc:oracle:thin:@tcps://<host>:<port>/<service_name>?wallet_location=Database_Wallet"
    username: "dbuser"
    password: "xxxxxx"
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: TransactionConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30
  # MicroTx properties
  microtx:
    lra:
      coordinator-url: http://localhost:9000/api/v1/lra-coordinator
      participant-url: http://localhost:8081
      propagation-active: true
      headers-propagation-prefix: { x-b3-, oracle-tmm-, authorization, refresh- }